AUDIO_DRIVER = pwm_hardware

DEFERRED_EXEC_ENABLE = yes

DEFAULT_FOLDER = elpekenin/access

RGB_MATRIX_CUSTOM_KB = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor

QUANTUM_PAINTER_DRIVERS += il91874_spi
QUANTUM_PAINTER_DRIVERS += ili9163_spi ili9341_spi ili9486_shiftreg_spi
