CUSTOM_MATRIX = lite

DEFERRED_EXEC_ENABLE = yes

QUANTUM_PAINTER_DRIVERS += il91874_spi ili9163_spi ili9341_spi

RGB_MATRIX_CUSTOM_KB = yes
RGB_MATRIX_DRIVER = WS2812
WS2812_DRIVER = vendor

SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

XAP_ENABLE = yes

# Custom features
CUSTOM_EEPROM = yes
TOUCH_SCREEN  = no
ONE_HAND      = no
SIPO_PINS     = yes
