name: Build firmware for keyboards
on:
  push:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-firmware:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - mlego/m65/rev1
          - mlego/m65/rev2
          - mlego/m65/rev3
          - mlego/m65/rev4
          - mlego/m65/rev5
          - mlego/m65/rev6
          - mlego/m65/rev7
          - mlego/m65/rev9
          - mlego/m65/rev10
        keymap:
          - default
          - uk
        include:
          - keyboard: 
              - mlego/m65/rev9
              - mlego/m65/rev10 
            keymap: 
             - default_knob
             - uk_knob 
          

    steps:
    - name: Checkout QMK Firmware
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        persist-credentials: false
        submodules: true

    - name: Build
      id: build
      run: |
        git config --global --add safe.directory '*'
        python3 -m pip install -r requirements-dev.txt
        make git-submodule
          if [ -d keyboards/${{ matrix.keyboard}}/keymap/${{ matrix.keymap }} ]; then
          qmk compile -kb ${{ matrix.keyboard}} -km ${{ matrix.keymap }}

          TARGET="$(echo "${{ matrix.keyboard }}" | sed 's#/#_#g')_${{matrix.keymap}}"
          echo "artifact-name=${TARGET}" >> $GITHUB_OUTPUT
          echo "Artifact-name: ${{ steps.build.outputs.artifact-name }}"
        fi 

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: "${{ steps.build.outputs.artifact-name }}"
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true
